http:
  routers:
    hsps-manager:
      rule: "Host(`hsps-manager.astrohweston.xyz`)"
      service: hsps-manager

  services:
    hsps-manager:
      loadBalancer:
        servers:
          - url: "http://65.21.157.66:2473"
        healthCheck:
          scheme: http
          path: /_health/
          interval: 30s
          timeout: 10s
        passHostHeader: true