http:
  routers:
    hsps-manager:
      rule: "Host(`hsps-manager.astrohweston.xyz`)"
      service: hsps-manager

  services:
    hsps-manager:
      loadBalancer:
        servers:
          - url: "http://65.21.157.66:2473"
        passHostHeader: true