http:
  routers:
    mailcow:
      rule: "Host(`mail.astrohweston.xyz`)"
      service: mailcow-svc

    mailcow-autoconfig:
      rule: "(Host(`autoconfig.astrohweston.xyz`) && Path(`/autodiscover/autodiscover.xml`))"
      service: mailcow-svc

    mailcow-autodiscover:
      rule: "(Host(`autodiscover.astrohweston.xyz`) && Path(`/mail/config-v1.1.xml`))"
      service: mailcow-svc

  services:
    mailcow:
      loadBalancer:
        servers:
          - url: "http://mailcow-nginx-mailcow-1:8080"